name: CI/CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  # install dependencies and run lint command
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3: install npm dependencies
      - name: Install dependencies
        run: npm ci

      # 4: run lint command
      - name: Run lint command
        run: npm run eslint

  # install dependencies and run test command
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3: install npm dependencies
      - name: Install dependencies
        run: npm ci

      # 4: run test command
      - name: Run test command

  Deploy-Production:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
