# workflow name
name: CI

# execute on events
on:
  push:
    branches:
      - main

# jobs to run
jobs:
  # install dependencies and run test command
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

       # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3: install npm dependencies
      - name: Install dependencies
        run: npm ci
      
      # 4: run lint command
      - name: Run lint command
        run: npm run eslint